repos:
  githubsuperservice:
      url: "https://raw.githubusercontent.com/7oku/sample-compose/main/compose-files/servicename/docker-compose.yaml"
basicauth:
  user1: "god"
loglevel: "error"
autosync: "on"
targetpath: "/tmp/opt/compose"
workdir: "/tmp/ocd"
