repos:
  githubsuperservice:
      url: "https://raw.githubusercontent.com/7oku/orcacd/main/compose-files/servicename/docker-compose.yaml"
basicauth:
  ocdadmin: "ocd1337god"
interval: 300
loglevel: "error"
autosync: "on"
targetpath: "/tmp/opt/compose"
workdir: "/tmp/ocd"
